version: '3.8'

services:
  app:
    image: 'credibanco:0.0.1'
    build:
      context: .
    container_name: credibanco_app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/credibanco
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

    ports:
      - '8080:8080'

  db:
    image: postgres
    container_name: credibanco_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=credibanco
    ports:
      - '5432:5432'